paths:
  'angular': 'angular/angular'
    # require angular mocks for testing
  'angular-mocks': 'angular-mocks/angular-mocks'
  # require restangular for easily handling sending and receiving request
  'restangular': 'restangular/dist/restangular'<% if (includeAngularAnimate) { %>
  # require angular animate for easily handling animation. I recommend to use this with tweenmax (bower install --save greensock)
  'angular-animate': 'angular-animate/angular-animate'<% } %>
  # require angular for better handling and binding controller
  'angular-ui-router': 'angular-ui-router/release/angular-ui-router'<% if (includeUIBootstrap) { %>
  # require ui-bootstrap with the embeded template [http://angular-ui.github.io/bootstrap/]
  'ui-bootstrap-tpls': 'angular-bootstrap/ui-bootstrap-tpls'<% }%>
  # require jquery
  'jquery': 'jquery'
  'jquery_ujs': 'jquery_ujs'<% if (includeLodash) { %>
  # require lodash
  'lodash': 'lodash/lodash'<% } %>
  # require bootstrap.js to make bootstrap components work
  'bootstrap': 'bootstrap-sprockets'
  # jasmine boostrap
  'jasmine': 'jasmine'
  'jasmine-html': 'jasmine-html'
  'jasmine-specs': 'jasmine-specs'
  'json2': 'json2'
  'boot': 'boot'
shim:
  'jquery_ujs': ['jquery']
  'angular':
    exports: 'angular'
    deps: ['jquery']
  'angular-mocks': ['angular']<% if (includeLodash) { %>
  'lodash':
    exports: '_'<% } %>
  'restangular': ['angular']<% if (includeAngularAnimate) { %>
  'angular-animate': ['angular']<% } %>
  'angular-ui-router': ['angular']<% if (includeUIBootstrap) { %>
  'ui-bootstrap-tpls': ['angular']<% } %>
  'bootstrap': ['jquery']
  # jasmine test bootstrap
  'jasmine':
    exports: 'window.jasmineRequire'
  'jasmine-html':
    deps: ['jasmine']
    exports: 'window.jasmineRequire'
  'jasmine-specs': ['boot']
  'boot':
    deps: ['jasmine', 'jasmine-html']
    exports: 'window.jasmineRequire'
